#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta8wifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gta8wifi/proprietary/vendor/atcmdlist:$(TARGET_COPY_OUT_VENDOR)/atcmdlist \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/BBAT.conf:$(TARGET_COPY_OUT_VENDOR)/etc/BBAT.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/PCBA.conf:$(TARGET_COPY_OUT_VENDOR)/etc/PCBA.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/SWPACInfo.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SWPACInfo.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/a2dpsink_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dpsink_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/adb.iso:$(TARGET_COPY_OUT_VENDOR)/etc/adb.iso \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/readme.txt:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/readme.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/analyzer.py:$(TARGET_COPY_OUT_VENDOR)/etc/analyzer.py \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_pskey.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_pskey.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_pskey_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_pskey_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_rf.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_rf.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_rf_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_rf_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/colortone_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/colortone_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/hdr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/hdr_face_detected_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_face_detected_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/mfnr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/deviceidle.xml:$(TARGET_COPY_OUT_VENDOR)/etc/deviceidle.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dpolicy:$(TARGET_COPY_OUT_VENDOR)/etc/dpolicy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/autotest.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/cali.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/normal_lite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal_lite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/agdsp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/agdsp.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/ap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/ap.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/cp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/cp.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/pc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/pc.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/sensorhub.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/sensorhub.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/wcn.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/wcn.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/3d_lut.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/abc.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/bld.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/cms.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/flash.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/flash.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/gamma.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/fm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/fm.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/fm_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/fm_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hearing_aid_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hqm_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hqm_device.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_chipset.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_chipset.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_hyper_permission.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_hyper_permission.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_vendor.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/lmkd_param.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lmkd_param.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/mlogservice.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mlogservice.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/modem_cp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_cp_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/modem_sp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_sp_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/nvmerge.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/nvmerge.cfg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/obj_disc.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/obj_disc.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/otpgoldendata.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/otpgoldendata.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/oz1_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/oz1_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/oz2_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/oz2_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/sale_after_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/sale_after_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/sell_aft_cali.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/sell_aft_cali.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/spw_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/spw_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/permissions/android.hardware.hardware_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.hardware_keystore.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/permissions/vendor_remove_telephony_features.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor_remove_telephony_features.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/playback_record_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/playback_record_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_info.db:$(TARGET_COPY_OUT_VENDOR)/etc/power_info.db \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_resource_file_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_file_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_resource_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_id_define.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_scene_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_scene_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_id_define.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/primary_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/primary_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/public.libraries.txt.backup:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt.backup \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/pwctl_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwctl_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/MeanFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/MeanFea.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/ParaFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/ParaFea.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmAgeFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmAgeModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmExpFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmExpModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmGenModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmGenderFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenderFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/scenario.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scenario.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-base-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-base-policy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-ext-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-ext-policy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/secnvm/k250a_00000200.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_00000200.img \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sensor_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sensor_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/situation_audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/situation_audio_policy_volumes_sec.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_autotest.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_cali.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_factory.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_factory.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_lite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_lite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/somxreg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/somxreg.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/spirentroot.cer:$(TARGET_COPY_OUT_VENDOR)/etc/spirentroot.cer \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sprd_hdr_tuning.param:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_hdr_tuning.param \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sprd_performance_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_performance_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/supl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/supl.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sysconfig/partner-apex-vendor-allowlist.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sysconfig/partner-apex-vendor-allowlist.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/tf_models/PortraitSegHP.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/tf_models/PortraitSegHP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/tf_models/PortraitSegLP.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/tf_models/PortraitSegLP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/traceconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/traceconfig.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/uniber.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uniber.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/unipnp/UniFeature.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/vramdiskd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vramdiskd.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_pskey.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_pskey.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_pskey_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_pskey_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_rf.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_rf.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_rf_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_rf_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/fm_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/fm_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/wifi_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/wifi_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/wifi_board_config_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/wifi_board_config_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wifi_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wifi_board_config_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi_board_config_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.debug:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.debug \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.factorytest:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.factorytest \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.user:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.user \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/yloglite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/yloglitesource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglitesource.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylogsource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ylogsource.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-495354535449.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-495354535449.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-496343475244.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-496343475244.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-4b45594d5354.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-4b45594d5354.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-53454d655345.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-53454d655345.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-6b6e78677564.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-6b6e78677564.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-4875-4171-496e-466163656871.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-4875-4171-496e-466163656871.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-4875-4171-496e-4772446d4871.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-4875-4171-496e-4772446d4871.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/Conf_MultipleTest_boe.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/Conf_MultipleTest_boe.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/EXEC_CALIBRATE_mmc5603:$(TARGET_COPY_OUT_VENDOR)/firmware/EXEC_CALIBRATE_mmc5603 \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/EXEC_CALIBRATE_qmc6308:$(TARGET_COPY_OUT_VENDOR)/firmware/EXEC_CALIBRATE_qmc6308 \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP.tflite:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP.tflite:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegMP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegMP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegMP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegMP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/aw882xx_pid_2013_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_pid_2013_acf.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/aw882xx_pid_2113_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_pid_2113_acf.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/facebeauty_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/facebeauty_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/faceid_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/faceid_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/fdr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fdr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/focaltech-FT5x46.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-FT5x46.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/focaltech_ts_fw_boe.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_boe.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hdr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hdr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_inx_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_inx_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_ls_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_ls_hsd_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_ls_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_ls_hsd_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_hsd_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_hsd_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_inx_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_inx_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_inx_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_ls_hsd_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_ls_hsd_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_xy_hsd_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_xy_hsd_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_xy_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_xy_inx_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/mfnr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfnr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_o.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_o.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_p.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_p.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_r.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_flv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_flv.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fp.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fv.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_mp.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_swid45_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_swid45_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_swid45_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_swid45_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/portraitseg_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/portraitseg_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/portraitseg_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/portraitseg_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/sechdcpapp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/sechdcpapp.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/vaultkeeper.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/vaultkeeper.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/vdsp_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vdsp_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/warp_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/warp_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_1000x200.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_1000x200.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_100x20.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_100x20.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_300x60.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_300x60.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_600x120.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_600x120.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_800x160.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_800x160.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_100x50x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_100x50x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_24x12x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_24x12x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_48x24x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_48x24x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_72x36x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_72x36x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/recovery-from-boot.p:$(TARGET_COPY_OUT_VENDOR)/recovery-from-boot.p

PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.1-resources \
    android.hardware.graphics.composer@2.2-resources \
    android.hardware.usb@1.3 \
    vendor.samsung.hardware.gnss@2.0-impl \
    libFaceAuth \
    libSecC2ComponentStore \
    libarcsoft_faceid \
    libavservices_minijail_vendor \
    libcodec2_sec_aacdec \
    libcodec2_sec_aacenc \
    libcodec2_sec_amrnbdec \
    libcodec2_sec_amrwbdec \
    libcodec2_sec_flacdec \
    libcodec2_sec_imadec \
    libcodec2_sec_mp3dec \
    libcodec2_sec_mp4vdec \
    libcodec2_sec_soft_common \
    libcodec2_sec_vc1dec \
    libcodec2_soft_ac4dec \
    libcodec2_soft_common \
    libcodec2_soft_eac3dec \
    libdeccfg \
    libdk_vnd_service_core \
    libengbt \
    libengmode15 \
    libengmode2lite \
    libengmode_client \
    libengmode_server \
    libengmode_tlc \
    libgrdm \
    libhyper \
    libkernelbootcp.trusty \
    libkeymaster4 \
    libkeymaster4_1support \
    libkeymaster4support \
    libkeymaster_helper \
    libkeymaster_messages \
    libkeymaster_portable \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    libmpbase \
    libpuresoftkeymasterdevice \
    libsec_semHalTlc \
    libsecril-client \
    libskeymaster4device \
    libsoft_attestation_cert \
    libsomxcmn \
    libsprdaudiohal@5.0 \
    libstork_shared \
    libteec \
    libtlc_comm_iccc \
    libtlc_direct_comm_iccc \
    libvkmanager_vendor \
    libvkservice \
    libvsp_ca \
    power.sprd \
    vendor.samsung.hardware.biometrics.face@2.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.light-V1-ndk_platform \
    vendor.samsung.hardware.miscpower@2.0 \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.engmode@1.0 \
    vendor.samsung.hardware.security.sem@1.0 \
    vendor.samsung.hardware.security.vaultkeeper@2.0 \
    vendor.samsung.hardware.security.widevine.keyprov-V1-ndk_platform \
    vendor.samsung.hardware.sysinput@1.0 \
    vendor.samsung.hardware.sysinput@1.1 \
    vendor.samsung.hardware.sysinput@1.2 \
    vendor.samsung.hardware.tlc.iccc@1.0-impl \
    vendor.samsung.hardware.tlc.iccc@1.0 \
    vendor.samsung.hardware.tlc.kg@1.0 \
    vendor.samsung.hardware.tlc.kg@1.1 \
    vendor.samsung.hardware.wifi.hostapd@3.0 \
    vendor.samsung.hardware.wifi.supplicant@3.0 \
    vendor.samsung.hardware.wifi@2.0 \
    vendor.samsung.hardware.wifi@2.1 \
    com.samsung.android.camera.unihal.signed \
    com.samsung.android.wifi.broadcom.signed \
    applypatch \
    btools \
    connmgr \
    connmgr_cli \
    cp_diskserver \
    cp_dump_dbg \
    cplay \
    cplogctl \
    cplogsvcctl \
    dcxsrv \
    emservice \
    engpc \
    engpcctl \
    enhance_test \
    factorytest \
    flush_slog_modem \
    fsdbg_vendor \
    gpsd \
    grdm_test \
    hal.json \
    hqread \
    android.hardware.audio.service \
    android.hardware.bluetooth@1.1-service.unisoc \
    android.hardware.camera.provider@2.4-service \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.graphics.composer@2.3-service \
    android.hardware.health@2.1-service-samsung \
    android.hardware.keymaster@4.0-service \
    android.hardware.memtrack@1.0-service \
    android.hardware.power.stats@1.0-service.mock \
    android.hardware.sensors@1.0-service \
    samsung.software.media.c2@1.0-service \
    vendor.samsung.hardware.biometrics.face@2.0-service \
    vendor.samsung.hardware.gnss@2.0-service \
    vendor.samsung.hardware.light-service \
    vendor.samsung.hardware.miscpower@2.0-service \
    vendor.samsung.hardware.security.drk@2.0-service \
    vendor.samsung.hardware.security.sem@1.0-service \
    vendor.samsung.hardware.security.widevine.keyprov-service \
    vendor.samsung.hardware.sysinput@1.2-service \
    vendor.samsung.hardware.tlc.iccc@1.0-service \
    vendor.samsung.hardware.tlc.kg@1.1-service \
    vendor.samsung.hardware.wifi@2.0-service \
    vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor.sprd.hardware.connmgr@1.0-service \
    vendor.unisoc.hardware.power-service \
    hwsim.json \
    hwsim_case.json \
    iod \
    iwnpi \
    json1_default.json \
    mlogservice \
    modem_control \
    modem_ctrl_dbg \
    nhMonitorCtrl \
    oem.json \
    phasecheckserver \
    fix_cpu_freq \
    lit_cpu_freq \
    cpu_loading \
    cpu_trans_table \
    ddr_bm \
    ddr_bm_log \
    sharkl5Pro_cm4_disable_smart_light.bin \
    fix_ddr_freq \
    ddr_loading \
    ddr_trans_table \
    fps_sf \
    fix_gpu_freq \
    gpu_loading \
    gpu_trans_table \
    interrupt \
    paras \
    tops \
    slogmodem_vendor \
    sprdstorageproxyd \
    srtd \
    storkd \
    tee_rpc \
    tsupplicant \
    uniber \
    vendor.samsung.hardware.security.engmode@1.0-service \
    vendor.samsung.hardware.security.vaultkeeper@2.0-service \
    wvkprov

ifneq ($(TARGET_IS_TABLET),true)

PRODUCT_COPY_FILES += \
    vendor/samsung/gta8wifi/proprietary/vendor/atcmdlist:$(TARGET_COPY_OUT_VENDOR)/atcmdlist \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/BBAT.conf:$(TARGET_COPY_OUT_VENDOR)/etc/BBAT.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/PCBA.conf:$(TARGET_COPY_OUT_VENDOR)/etc/PCBA.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/SWPACInfo.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SWPACInfo.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/adb.iso:$(TARGET_COPY_OUT_VENDOR)/etc/adb.iso \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_0_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_0_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_CAP_1_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_CAP_1_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_0_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_0_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_PREV_1_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_PREV_1_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_0_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_0_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_0.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_0.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_1.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_1.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_2.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_2.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_3.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_3.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/BG_VID_1_4.bmp:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/BG_VID_1_4.bmp \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/common/readme.txt:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/common/readme.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_0_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_0_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_0.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_1.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_1.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_2.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_2.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_3.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_3.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/aiimg/front/BG_CAP_1_4.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/aiimg/front/BG_CAP_1_4.jpg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/analyzer.py:$(TARGET_COPY_OUT_VENDOR)/etc/analyzer.py \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_pskey.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_pskey.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_pskey_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_pskey_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_rf.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_rf.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/bt_configure_rf_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/bt_configure_rf_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/colortone_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/colortone_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/hdr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/hdr_face_detected_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_face_detected_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/camera/mfnr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_arrays.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/deviceidle.xml:$(TARGET_COPY_OUT_VENDOR)/etc/deviceidle.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/dpolicy:$(TARGET_COPY_OUT_VENDOR)/etc/dpolicy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/autotest.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/cali.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/chnl/normal_lite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal_lite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/agdsp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/agdsp.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/ap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/ap.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/cp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/cp.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/pc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/pc.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/sensorhub.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/sensorhub.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/engpc/dev/wcn.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/wcn.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/3d_lut.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/abc.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/bld.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/cms.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/flash.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/flash.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/enhance/gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/gamma.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/fm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/fm.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/fm_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/fm_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hearing_aid_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hqm_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hqm_device.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_chipset.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_chipset.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_hyper_permission.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_hyper_permission.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/hyper/config_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_vendor.json \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/lmkd_param.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lmkd_param.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/mlogservice.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mlogservice.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/modem_cp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_cp_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/modem_sp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_sp_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/nvmerge.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/nvmerge.cfg \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/obj_disc.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/obj_disc.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/otpgoldendata.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/otpgoldendata.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/oz1_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/oz1_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/oz2_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/oz2_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/sale_after_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/sale_after_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/sell_aft_cali.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/sell_aft_cali.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/otpdata/spw_input_parameters_values.txt:$(TARGET_COPY_OUT_VENDOR)/etc/otpdata/spw_input_parameters_values.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/permissions/android.hardware.hardware_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.hardware_keystore.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/permissions/vendor_remove_telephony_features.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor_remove_telephony_features.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/playback_record_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/playback_record_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_info.db:$(TARGET_COPY_OUT_VENDOR)/etc/power_info.db \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_resource_file_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_file_info.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_resource_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_id_define.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_scene_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/power_scene_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_id_define.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/primary_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/primary_audio_policy_configuration.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/public.libraries.txt.backup:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt.backup \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/pwctl_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwctl_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/MeanFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/MeanFea.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/ParaFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/ParaFea.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmAgeFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmAgeModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmExpFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmExpModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmGenModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenModel.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/saiv/gae/PmGenderFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenderFeatSelIdx.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/scenario.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scenario.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-base-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-base-policy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-ext-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-ext-policy \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/secnvm/k250a_00000200.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_00000200.img \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sensor_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sensor_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/situation_audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/situation_audio_policy_volumes_sec.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_autotest.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_cali.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_factory.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_factory.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/slog_modem_lite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_lite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/somxreg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/somxreg.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/spirentroot.cer:$(TARGET_COPY_OUT_VENDOR)/etc/spirentroot.cer \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sprd_hdr_tuning.param:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_hdr_tuning.param \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sprd_performance_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_performance_config.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/supl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/supl.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/sysconfig/partner-apex-vendor-allowlist.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sysconfig/partner-apex-vendor-allowlist.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/tf_models/PortraitSegHP.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/tf_models/PortraitSegHP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/tf_models/PortraitSegLP.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/tf_models/PortraitSegLP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/traceconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/traceconfig.txt \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/uniber.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uniber.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/unipnp/UniFeature.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/vramdiskd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vramdiskd.xml \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_pskey.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_pskey.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_pskey_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_pskey_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_rf.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_rf.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/bt_configure_rf_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/bt_configure_rf_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/fm_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/fm_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/wifi_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/wifi_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wcn/wifi_board_config_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn/wifi_board_config_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wifi_board_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi_board_config.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/wifi_board_config_aa.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi_board_config_aa.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.debug:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.debug \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.factorytest:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.factorytest \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylog.conf.user:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.user \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/yloglite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglite.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/yloglitesource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglitesource.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/etc/ylogsource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ylogsource.conf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-495354535449.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-495354535449.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-496343475244.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-496343475244.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-4b45594d5354.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-4b45594d5354.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-53454d655345.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-53454d655345.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-0000-0000-0000-6b6e78677564.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-0000-0000-0000-6b6e78677564.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-4875-4171-496e-466163656871.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-4875-4171-496e-466163656871.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/00000000-4875-4171-496e-4772446d4871.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/00000000-4875-4171-496e-4772446d4871.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/Conf_MultipleTest_boe.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/Conf_MultipleTest_boe.ini \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/EXEC_CALIBRATE_mmc5603:$(TARGET_COPY_OUT_VENDOR)/firmware/EXEC_CALIBRATE_mmc5603 \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/EXEC_CALIBRATE_qmc6308:$(TARGET_COPY_OUT_VENDOR)/firmware/EXEC_CALIBRATE_qmc6308 \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP.tflite:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegHP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegHP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP.tflite:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP.tflite \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegLP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegLP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegMP_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegMP_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/PortraitSegMP_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/PortraitSegMP_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/aw882xx_pid_2013_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_pid_2013_acf.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/aw882xx_pid_2113_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_pid_2113_acf.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/facebeauty_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/facebeauty_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/faceid_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/faceid_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/fdr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fdr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/focaltech-FT5x46.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-FT5x46.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/focaltech_ts_fw_boe.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_boe.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hdr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hdr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_inx_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_inx_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_ls_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_ls_hsd_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_ls_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_ls_hsd_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_hsd_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_hsd_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_inx_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx83102e_xy_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xy_inx_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_inx_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_ls_hsd_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_ls_hsd_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_xy_hsd_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_xy_hsd_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/hx_xy_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_xy_inx_criteria.csv \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/mfnr_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfnr_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_o.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_o.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_p.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_p.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fd_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fd_r.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_flv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_flv.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fp.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/network_coeff_fv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/network_coeff_fv.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_mp.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_swid45_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_swid45_fw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/nt36523b_qc_inx_swid45_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523b_qc_inx_swid45_mpfw.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/portraitseg_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/portraitseg_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/portraitseg_network.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/portraitseg_network.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/sechdcpapp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/sechdcpapp.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/vaultkeeper.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/vaultkeeper.elf \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/vdsp_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vdsp_firmware.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/firmware/warp_cadence.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/warp_cadence.bin \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_1000x200.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_1000x200.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_100x20.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_100x20.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_300x60.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_300x60.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_600x120.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_600x120.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/logo_800x160.rgba:$(TARGET_COPY_OUT_VENDOR)/logo/logo_800x160.rgba \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_100x50x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_100x50x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_24x12x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_24x12x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_48x24x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_48x24x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/logo/time_vert_72x36x13.yuv:$(TARGET_COPY_OUT_VENDOR)/logo/time_vert_72x36x13.yuv \
    vendor/samsung/gta8wifi/proprietary/vendor/recovery-from-boot.p:$(TARGET_COPY_OUT_VENDOR)/recovery-from-boot.p

PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.1-resources \
    android.hardware.graphics.composer@2.2-resources \
    android.hardware.usb@1.3 \
    vendor.samsung.hardware.gnss@2.0-impl \
    libFaceAuth \
    libSecC2ComponentStore \
    libarcsoft_faceid \
    libavservices_minijail_vendor \
    libcodec2_sec_aacdec \
    libcodec2_sec_aacenc \
    libcodec2_sec_amrnbdec \
    libcodec2_sec_amrwbdec \
    libcodec2_sec_flacdec \
    libcodec2_sec_imadec \
    libcodec2_sec_mp3dec \
    libcodec2_sec_mp4vdec \
    libcodec2_sec_soft_common \
    libcodec2_sec_vc1dec \
    libcodec2_soft_ac4dec \
    libcodec2_soft_common \
    libcodec2_soft_eac3dec \
    libdeccfg \
    libdk_vnd_service_core \
    libengbt \
    libengmode15 \
    libengmode2lite \
    libengmode_client \
    libengmode_server \
    libengmode_tlc \
    libgrdm \
    libhyper \
    libkernelbootcp.trusty \
    libkeymaster4 \
    libkeymaster4_1support \
    libkeymaster4support \
    libkeymaster_helper \
    libkeymaster_messages \
    libkeymaster_portable \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    libmpbase \
    libpuresoftkeymasterdevice \
    libsec_semHalTlc \
    libsecril-client \
    libskeymaster4device \
    libsoft_attestation_cert \
    libsomxcmn \
    libsprdaudiohal@5.0 \
    libstork_shared \
    libteec \
    libtlc_comm_iccc \
    libtlc_direct_comm_iccc \
    libvkmanager_vendor \
    libvkservice \
    libvsp_ca \
    power.sprd \
    vendor.samsung.hardware.biometrics.face@2.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.light-V1-ndk_platform \
    vendor.samsung.hardware.miscpower@2.0 \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.engmode@1.0 \
    vendor.samsung.hardware.security.sem@1.0 \
    vendor.samsung.hardware.security.vaultkeeper@2.0 \
    vendor.samsung.hardware.security.widevine.keyprov-V1-ndk_platform \
    vendor.samsung.hardware.sysinput@1.0 \
    vendor.samsung.hardware.sysinput@1.1 \
    vendor.samsung.hardware.sysinput@1.2 \
    vendor.samsung.hardware.tlc.iccc@1.0-impl \
    vendor.samsung.hardware.tlc.iccc@1.0 \
    vendor.samsung.hardware.tlc.kg@1.0 \
    vendor.samsung.hardware.tlc.kg@1.1 \
    vendor.samsung.hardware.wifi.hostapd@3.0 \
    vendor.samsung.hardware.wifi.supplicant@3.0 \
    vendor.samsung.hardware.wifi@2.0 \
    vendor.samsung.hardware.wifi@2.1 \
    com.samsung.android.camera.unihal.signed \
    com.samsung.android.wifi.broadcom.signed \
    applypatch \
    btools \
    connmgr \
    connmgr_cli \
    cp_diskserver \
    cp_dump_dbg \
    cplay \
    cplogctl \
    cplogsvcctl \
    dcxsrv \
    emservice \
    engpc \
    engpcctl \
    enhance_test \
    factorytest \
    flush_slog_modem \
    fsdbg_vendor \
    gpsd \
    grdm_test \
    hal.json \
    hqread \
    android.hardware.audio.service \
    android.hardware.bluetooth@1.1-service.unisoc \
    android.hardware.camera.provider@2.4-service \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.graphics.composer@2.3-service \
    android.hardware.health@2.1-service-samsung \
    android.hardware.keymaster@4.0-service \
    android.hardware.memtrack@1.0-service \
    android.hardware.power.stats@1.0-service.mock \
    android.hardware.sensors@1.0-service \
    samsung.software.media.c2@1.0-service \
    vendor.samsung.hardware.biometrics.face@2.0-service \
    vendor.samsung.hardware.gnss@2.0-service \
    vendor.samsung.hardware.light-service \
    vendor.samsung.hardware.miscpower@2.0-service \
    vendor.samsung.hardware.security.drk@2.0-service \
    vendor.samsung.hardware.security.sem@1.0-service \
    vendor.samsung.hardware.security.widevine.keyprov-service \
    vendor.samsung.hardware.sysinput@1.2-service \
    vendor.samsung.hardware.tlc.iccc@1.0-service \
    vendor.samsung.hardware.tlc.kg@1.1-service \
    vendor.samsung.hardware.wifi@2.0-service \
    vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor.sprd.hardware.connmgr@1.0-service \
    vendor.unisoc.hardware.power-service \
    hwsim.json \
    hwsim_case.json \
    iod \
    iwnpi \
    json1_default.json \
    mlogservice \
    modem_control \
    modem_ctrl_dbg \
    nhMonitorCtrl \
    oem.json \
    phasecheckserver \
    fix_cpu_freq \
    lit_cpu_freq \
    cpu_loading \
    cpu_trans_table \
    ddr_bm \
    ddr_bm_log \
    sharkl5Pro_cm4_disable_smart_light.bin \
    fix_ddr_freq \
    ddr_loading \
    ddr_trans_table \
    fps_sf \
    fix_gpu_freq \
    gpu_loading \
    gpu_trans_table \
    interrupt \
    paras \
    tops \
    slogmodem_vendor \
    sprdstorageproxyd \
    srtd \
    storkd \
    tee_rpc \
    tsupplicant \
    uniber \
    vendor.samsung.hardware.security.engmode@1.0-service \
    vendor.samsung.hardware.security.vaultkeeper@2.0-service \
    wvkprov

endif
